version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gestao_cacambas_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_cacambas
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
